In [19]:
import pandas as pd
import numpy as np
df=pd.read_csv("online_retail_practice_sample.csv")
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [20]:
df_raw=df.copy()
df_raw=df_raw.rename(columns={
    'Description':'ProductDescription'
})
df_raw

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [21]:
df_raw['Revenue'] = df_raw['Quantity'] * df_raw['UnitPrice']
df_raw
# print(df_raw[['Quantity', 'UnitPrice', 'Revenue']])

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden,28.49
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden,59.50
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands,0.00
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain,40.68
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden,50.85
...,...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain,59.50
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE,165.75
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain,-35.70
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal,20.40
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany,15.30

In [26]:
con = [
    df_raw['InvoiceNo'].str.startswith('C', na=False),
    df_raw['Quantity'] < 0,
    (df_raw['Quantity'] > 0) & (df_raw['UnitPrice'] >= 0)
]

choices = ['Cancellation', 'Return', 'Positive Sale']

df_raw['TransactionType'] = np.select(
    con,
    choices,
    default='Other/Invalid'
)
df_raw

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,IsIdentifiedCustomer,TransactionType
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden,28.49,True,Positive Sale
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden,59.50,True,Positive Sale
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands,0.00,True,Other/Invalid
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain,40.68,True,Positive Sale
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden,50.85,True,Positive Sale
...,...,...,...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain,59.50,True,Positive Sale
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE,165.75,True,Positive Sale
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain,-35.70,True,Cancellation
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal,20.40,True,Positive Sale
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany,15.30,True,Positive Sale

In [27]:
df_raw['IsIdentifiedCustomer'] = df_raw['CustomerID'].notna()
df_raw

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,IsIdentifiedCustomer,TransactionType
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden,28.49,True,Positive Sale
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden,59.50,True,Positive Sale
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands,0.00,True,Other/Invalid
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain,40.68,True,Positive Sale
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden,50.85,True,Positive Sale
...,...,...,...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain,59.50,True,Positive Sale
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE,165.75,True,Positive Sale
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain,-35.70,True,Cancellation
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal,20.40,True,Positive Sale
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany,15.30,True,Positive Sale

In [28]:
df_raw['InvoiceDate']=pd.to_datetime(
    df_raw['InvoiceDate']
)
df_raw

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,IsIdentifiedCustomer,TransactionType
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden,28.49,True,Positive Sale
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden,59.50,True,Positive Sale
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands,0.00,True,Other/Invalid
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain,40.68,True,Positive Sale
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden,50.85,True,Positive Sale
...,...,...,...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain,59.50,True,Positive Sale
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE,165.75,True,Positive Sale
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain,-35.70,True,Cancellation
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal,20.40,True,Positive Sale
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany,15.30,True,Positive Sale

In [25]:
df_raw['InvoiceNo'] = df_raw['InvoiceNo'].astype('string')
df_raw['StockCode'] = df_raw['StockCode'].astype('string')
df_raw['Country'] = df_raw['Country'].astype('string')
df_raw.dtypes

InvoiceNo                       string
StockCode                       string
ProductDescription                 str
Quantity                         int64
InvoiceDate             datetime64[us]
UnitPrice                      float64
CustomerID                     float64
Country                         string
Revenue                        float64
IsIdentifiedCustomer              bool
dtype: object

In [33]:
df_raw=df_raw.sort_values(by=['InvoiceDate','InvoiceNo'],ascending=[True,True])
df_raw

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,IsIdentifiedCustomer,TransactionType
1523,569444,71053,WHITE METAL LANTERN,15,2010-12-01 00:05:00,3.39,13845.0,Germany,50.85,True,Positive Sale
122,C543863,84406B,CREAM CUPID HEARTS COAT HANGER,-13,2010-12-01 02:26:00,2.75,14319.0,France,-35.75,True,Cancellation
409,568184,84406B,CREAM CUPID HEARTS COAT HANGER,3,2010-12-01 03:57:00,2.20,15058.0,France,6.60,True,Positive Sale
78,C551232,71053,WHITE METAL LANTERN,-7,2010-12-01 06:06:00,4.07,12472.0,Spain,-28.49,True,Cancellation
1312,536850,22423,REGENCY CAKESTAND 3 TIER,9,2010-12-01 21:38:00,10.20,12972.0,Sweden,91.80,True,Positive Sale
...,...,...,...,...,...,...,...,...,...,...,...
1532,558153,84406B,CREAM CUPID HEARTS COAT HANGER,8,2011-12-08 04:14:00,2.75,12313.0,Sweden,22.00,True,Positive Sale
831,542017,85123A,WHITE HANGING HEART T-LIGHT HOLDER,2,2011-12-08 06:50:00,3.06,13029.0,France,6.12,True,Positive Sale
1161,544435,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2011-12-08 07:15:00,5.10,15446.0,Netherlands,30.60,True,Positive Sale
801,572572,79323P,PINK CHERRY LIGHTS,5,2011-12-08 17:37:00,6.75,12426.0,Belgium,33.75,True,Positive Sale
21,579630,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-12-08 18:19:00,3.39,13148.0,Germany,50.85,True,Positive Sale

In [35]:
df_raw = df_raw.reset_index(drop=True)

print(df_raw.index)
print(df_raw.index.equals(pd.RangeIndex(len(df))))
print(df_raw.head())
df_raw.to_csv("Output_p_4.csv")

RangeIndex(start=0, stop=1612, step=1)
True
  InvoiceNo StockCode              ProductDescription  Quantity  \
0    569444     71053             WHITE METAL LANTERN        15
1   C543863    84406B  CREAM CUPID HEARTS COAT HANGER       -13
2    568184    84406B  CREAM CUPID HEARTS COAT HANGER         3
3   C551232     71053             WHITE METAL LANTERN        -7
4    536850     22423        REGENCY CAKESTAND 3 TIER         9

          InvoiceDate  UnitPrice  CustomerID  Country  Revenue  \
0 2010-12-01 00:05:00       3.39     13845.0  Germany    50.85
1 2010-12-01 02:26:00       2.75     14319.0   France   -35.75
2 2010-12-01 03:57:00       2.20     15058.0   France     6.60
3 2010-12-01 06:06:00       4.07     12472.0    Spain   -28.49
4 2010-12-01 21:38:00      10.20     12972.0   Sweden    91.80

   IsIdentifiedCustomer TransactionType
0                  True   Positive Sale
1                  True    Cancellation
2                  True   Positive Sale
3                  True    Cancellation
4                  True   Positive Sale